# SPDX-License-Identifier: MIT-0
---
- name: DROP OLD RECORDS
  ansible.builtin.include_tasks: delete_records.yml
  vars:
    current_item: "{{ item }}"
  with_items: "{{ playload }}"

- name: CREATE NEW RECORDS
  ansible.builtin.uri:
    url: "https://api.alwaysdata.com/v1/record/"
    force_basic_auth: true
    user: "{{ alwaysdata_token }}:"
    password: ""
    method: POST
    status_code: 201
    body_format: json
    follow_redirects: all
    return_content: true

    headers:
      Content-Type: 'application/json'
      Accept: "*/*"
    body:
      domain: "{{ item.alwaysdata_domain_id }}"
      type: "{{ record_type }}"
      name: "{{ item.name }}"
      value: "{{ vars[item.dns] }}"
      ttl: 0
      annotation: "{{ annotation }}"
    # validate_certs: false
  register: dns_records_add
  with_items: "{{ playload }}"
  when: "(not delete) and ('alwaysdata_domain_id' in item)"

# tasks file for alwaysdata_records
...
